image:
  file: .gitpod.Dockerfile
github:  
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
tasks:
  - name: Install Python Packages
    init: |
      pip install --upgrade pip
      pip install -r ./requirements.txt
      pip install -e .
vscode:
  extensions:
    - "ms-python.python"
    - "ms-azuretools.vscode-docker"
    - "mechatroner.rainbow-csv"